In [11]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [12]:
irisdata= datasets.load_iris()
X_train,X_test,y_train,y_test = train_test_split(irisdata.data, irisdata.target,test_size=0.3,random_state=109)

In [13]:
from sklearn import svm
svclassifier=svm.SVC(kernel='poly',degree=8)
svclassifier.fit(X_train,y_train)
y_pred=svclassifier.predict(X_test)

In [19]:
from sklearn.metrics import classification_report, confusion_matrix
cm=confusion_matrix(y_pred, y_test)
print("confusion matrix :",cm)
print("Classification Report",classification_report(y_pred, y_test))

confusion matrix : [[12  0  0]
 [ 0 15  1]
 [ 0  2 15]]
Classification Report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.88      0.94      0.91        16
           2       0.94      0.88      0.91        17

    accuracy                           0.93        45
   macro avg       0.94      0.94      0.94        45
weighted avg       0.93      0.93      0.93        45



In [20]:
svclassifier=svm.SVC(kernel='linear',degree=8)
svclassifier.fit(X_train,y_train)
y_pred=svclassifier.predict(X_test)

In [21]:
cm=confusion_matrix(y_pred, y_test)
print("confusion matrix :",cm)
print("Classification Report",classification_report(y_pred, y_test))

confusion matrix : [[12  0  0]
 [ 0 15  0]
 [ 0  2 16]]
Classification Report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.88      1.00      0.94        15
           2       1.00      0.89      0.94        18

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45



In [22]:
svclassifier=svm.SVC(kernel='rbf',degree=8)
svclassifier.fit(X_train,y_train)
y_pred=svclassifier.predict(X_test)

In [23]:
cm=confusion_matrix(y_pred, y_test)
print("confusion matrix :",cm)
print("Classification Report",classification_report(y_pred, y_test))

confusion matrix : [[12  0  0]
 [ 0 16  3]
 [ 0  1 13]]
Classification Report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.94      0.84      0.89        19
           2       0.81      0.93      0.87        14

    accuracy                           0.91        45
   macro avg       0.92      0.92      0.92        45
weighted avg       0.92      0.91      0.91        45

