In [ ]:
# Vignesh S - 19BEC1391
# Decision Tree without Inbuilt func.

In [14]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [15]:
def train_using_gini(X_train,X_test,y_train):
  clf_gini=DecisionTreeClassifier(criterion="gini",random_state=100,max_depth=3,min_samples_leaf=5)
  clf_gini.fit(X_train,y_train)
  return clf_gini

In [16]:
def train_using_entropy(X_train,X_test,y_train):
  clf_entropy=DecisionTreeClassifier(criterion="entropy",random_state=100,max_depth=3,min_samples_leaf=5)
  clf_entropy.fit(X_train,y_train)
  return clf_entropy

In [17]:
def prediction(X_test,clf_object):
  y_pred=clf_object.predict(X_test)
  print("predicted values:")
  print(y_pred)
  return y_pred

In [18]:
def cal_accuracy(y_test,y_pred):
  print("confusion matrix:",confusion_matrix(y_test,y_pred))
  print("accuracy:",accuracy_score(y_test,y_pred))
  print("report:",classification_report(y_test,y_pred))

In [19]:
balance_data=pd.read_csv('Iris.csv')
print("dataset length:",len(balance_data))
print("dataset_shape:",balance_data.shape)

dataset length: 150
dataset_shape: (150, 6)


In [20]:
balance_data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [21]:
X=balance_data.values[:,0:4]
Y=balance_data.values[:,-1]

In [22]:
Y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [23]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=100)
clf_gini=train_using_gini(X_train,X_test,y_train)
clf_entropy=train_using_entropy(X_train,X_test,y_train)
print("results using gini index:")
y_pred_gini=prediction(X_test,clf_gini)
cal_accuracy(y_test,y_pred_gini)
y_pred_entropy=prediction(X_test,clf_entropy)
cal_accuracy(y_test,y_pred_entropy)


results using gini index:
predicted values:
['Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa']
confusion matrix: [[16  0  0]
 [ 0 11  0]
 [ 0  0 18]]
accuracy: 1.0
report:                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       1

In [24]:
X

array([[1, 5.1, 3.5, 1.4],
       [2, 4.9, 3.0, 1.4],
       [3, 4.7, 3.2, 1.3],
       [4, 4.6, 3.1, 1.5],
       [5, 5.0, 3.6, 1.4],
       [6, 5.4, 3.9, 1.7],
       [7, 4.6, 3.4, 1.4],
       [8, 5.0, 3.4, 1.5],
       [9, 4.4, 2.9, 1.4],
       [10, 4.9, 3.1, 1.5],
       [11, 5.4, 3.7, 1.5],
       [12, 4.8, 3.4, 1.6],
       [13, 4.8, 3.0, 1.4],
       [14, 4.3, 3.0, 1.1],
       [15, 5.8, 4.0, 1.2],
       [16, 5.7, 4.4, 1.5],
       [17, 5.4, 3.9, 1.3],
       [18, 5.1, 3.5, 1.4],
       [19, 5.7, 3.8, 1.7],
       [20, 5.1, 3.8, 1.5],
       [21, 5.4, 3.4, 1.7],
       [22, 5.1, 3.7, 1.5],
       [23, 4.6, 3.6, 1.0],
       [24, 5.1, 3.3, 1.7],
       [25, 4.8, 3.4, 1.9],
       [26, 5.0, 3.0, 1.6],
       [27, 5.0, 3.4, 1.6],
       [28, 5.2, 3.5, 1.5],
       [29, 5.2, 3.4, 1.4],
       [30, 4.7, 3.2, 1.6],
       [31, 4.8, 3.1, 1.6],
       [32, 5.4, 3.4, 1.5],
       [33, 5.2, 4.1, 1.5],
       [34, 5.5, 4.2, 1.4],
       [35, 4.9, 3.1, 1.5],
       [36, 5.0, 3.2, 1.2],
 

In [25]:
balance_data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]